### ISSUE TITLE
Country/language radio button

### ISSUE THREAD

**Issue by Mehonoshin** [khusnetdinov/nimbusex#2]
I would be great to have a helper for selecting language/country, displayed with flags.

E.g. the following form has a field for selecting post language [http://take.ms/PUbCb](http://take.ms/PUbCb)

Alternative approach, is to display select component with flags and names of languages.

@khusnetdinov thoughts?

**Comment by khusnetdinov** [comment]
It relate to form witch create change set, and it had better to create radio group with locales flags. See locales it can help with implementation
